import { useState } from "react";
import { Handle, Position } from "reactflow";
import { elevenLabsTTS } from "../../utils/ai";

export function VoiceOverNode() {
  const [text, setText] = useState("");
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const onTTS = async () => {
    setLoading(true);
    setError(null);
    try {
      const url = await elevenLabsTTS(text || "This is a sample voice over generated by nemo3.");
      setAudioUrl(url);
    } catch (e: unknown) {
      setError((e as Error).message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="relative px-3 py-2 bg-zinc-900/95 border border-zinc-800 rounded-lg shadow text-white w-64 select-none">
      <Handle type="target" position={Position.Left} className="!w-2 !h-2 !bg-yellow-400" />
      <div className="text-sm font-semibold leading-none mb-1">Generate Voice Over</div>
      <div className="text-[11px] text-zinc-400 mb-2">Paste script text, generate audio.</div>
      <textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder="Text to speak..."
        className="w-full h-20 text-xs bg-zinc-800 border border-zinc-700 rounded px-2 py-1 mb-2 outline-none resize-none"
      />
      <button
        onClick={onTTS}
        disabled={loading}
        className="text-[11px] px-2 py-1 rounded bg-yellow-400 text-black disabled:opacity-60"
      >
        {loading ? "Generating..." : "Generate Voice"}
      </button>
      {loading && (
        <div className="mt-2 text-[11px] text-yellow-400 animate-pulse">Generating audio...</div>
      )}
      {error && <div className="text-[11px] text-red-400 mt-2">{error}</div>}
      {audioUrl && (
        <audio src={audioUrl} controls className="mt-2 w-full" />
      )}
      <Handle type="source" position={Position.Right} className="!w-2 !h-2 !bg-yellow-400" />
    </div>
  );
}
